apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  SPRING_PROFILES_ACTIVE: {{ .active }}
  SERVER_PORT: {{ .server_port }}
  EMAIL_SERVICE_ENDPOINT: {{ .email_service }}
  COMPANY_SERVICE_ENDPOINT: {{ .company_service }}
  ACCOUNT_SERVICE_ENDPOINT: {{ .account_service }}
  BOT_SERVICE_ENDPOINT: {{ .bot_service }}
  SMS_SERVICE_ENDPOINT: {{ .sms_service }}
  SENTRY_DSN: {{ .sentry_dsn }}
  SIGNING_SECRET: {{ .signing_secret }}
  INTERCOM_ACCESS_TOKEN: {{ .intercom_access_token }}
  INTERCOM_APP_ID: {{ .intercom_app_id}}
  INTERCOM_SIGNING_SECRET: {{ .intercom_signing_secret }}
  ALIYUN_ACCESS_KEY: {{ .aliyun_access_key }}
  ALIYUN_ACCESS_SECRET: {{ .aliyun_access_secret }}
  RECAPTCHA_PUBLIC: {{ .recaptcha_public }}
  RECAPTCHA_PRIVATE: {{ .recaptcha_private }}
  ACCOUNT_DATASOURCE_URL: {{ .account_datasource_url }}
  ACCOUNT_DATASOURCE_USERNAME: {{ .account_datasource_username }}
  ACCOUNT_DATASOURCE_PASSWORD: {{ .account_datasource_password }}
  COMPANY_DATASOURCE_URL: {{ .company_datasource_url }}
  COMPANY_DATASOURCE_USERNAME: {{ .company_datasource_username }}
  COMPANY_DATASOURCE_PASSWORD: {{ .company_datasource_password }}